//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnpmNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChuyenBay()
        {
            this.ChiTietBays = new HashSet<ChiTietBay>();
            this.DatVes = new HashSet<DatVe>();
            this.HanhKhaches = new HashSet<HanhKhach>();
        }
    
        public string MaChuyenBay { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public System.TimeSpan GioKhoiHanh { get; set; }
        public System.DateTime NgayHaCanh { get; set; }
        public System.TimeSpan GioHaCanh { get; set; }
        public int SLGheTrong { get; set; }
        public decimal GiaVe { get; set; }
        public string TinhTrang { get; set; }
        public int GioBay { get; set; }
        public int PhutBay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBay> ChiTietBays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatVe> DatVes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhKhach> HanhKhaches { get; set; }
        public virtual SanBay SanBay { get; set; }
        public virtual SanBay SanBay1 { get; set; }
    }
}
