//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnpmNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatVe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatVe()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HanhKhaches = new HashSet<HanhKhach>();
        }
    
        public string MaDatVe { get; set; }
        public string MaChuyenBay { get; set; }
        public int SoLuongVe { get; set; }
        public string TaiKhoanDat { get; set; }
        public string TrangThai { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhKhach> HanhKhaches { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual HuyVe HuyVe { get; set; }
    }
}
