//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnpmNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HanhKhach
    {
        public string MaHK { get; set; }
        public string MaChuyenBay { get; set; }
        public string MaDatVe { get; set; }
        public string TenHK { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QuocTich { get; set; }
        public string CCCD { get; set; }
    
        public virtual ChuyenBay ChuyenBay { get; set; }
        public virtual DatVe DatVe { get; set; }
    }
}
