//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnpmNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeChuyenBay
    {
        public string MaVe { get; set; }
        public string MaDatVe { get; set; }
        public string MaHD { get; set; }
        public string MaHK { get; set; }
        public string TenHanhKhach { get; set; }
        public string MaChuyenBay { get; set; }
        public System.DateTime NgayKhoiHanh { get; set; }
        public System.TimeSpan GioKhoiHanh { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
    
        public virtual SanBay SanBay { get; set; }
        public virtual SanBay SanBay1 { get; set; }
    }
}
